Update adaptiveCardPrompt.ts
mdrichardson/botbuilder-js pull request #1
Opened 2019-07-01 23:49 UTC by v-kydela

## Description

Mostly formatting changes and refactoring.

2019-07-02 00:15 UTC, mdrichardson commented
Cool cool. I haven't reviewed it yet, but:

* Have you run the tests for it?
* Do you plan to make the same changes to C#?
* If so, would you prefer I review this one first, or both together once C# is done?

2019-07-02 15:13 UTC, mdrichardson requested changes
Just a couple pedantic changes that were my fault anyway. Overall, great code review. Nice cleanup.

2019-07-02 15:13 UTC, mdrichardson commented on libraries/botbuilder-dialogs/src/prompts/adaptiveCardPrompt.ts
> +        const state: any = dc.activeDialog.state as AdaptiveCardPromptState;
This is my fault, but can you change `any` to `AdaptiveCardPromptState`, then remove `as AdaptiveCardPromptState`

2019-07-02 15:13 UTC, mdrichardson commented on libraries/botbuilder-dialogs/src/prompts/adaptiveCardPrompt.ts
> +        const state: AdaptiveCardPromptState = dc.activeDialog.state as AdaptiveCardPromptState;
Also my fault. Remove `as AdaptiveCardPromptState`. I believe it's redundant.

2019-07-02 15:50 UTC, mdrichardson approved these changes
Nice! Tests pass

2019-07-02 15:50 UTC, merged

2019-07-12 14:53 UTC, mdrichardson commented
@v-kydela 	Were you planning on making the same updates to the C# version? I can; just don't want to double-commit

2019-07-12 15:48 UTC, v-kydela commented
@mdrichardson - You go ahead